"use client";

import { Suspense, useState, useEffect } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { ShieldCheck, Laptop, CheckCircle2, AlertCircle, Loader2, ArrowRight } from "lucide-react";
import { verifyDeviceCode } from "../../src/lib/api/auth";
import Link from "next/link";

function PairDeviceContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const initialCode = searchParams.get("code") || "";

  const [code, setCode] = useState(initialCode);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  useEffect(() => {
    if (initialCode) {
      setCode(initialCode.toUpperCase());
    }
  }, [initialCode]);

  async function handleApprove(e?: React.FormEvent) {
    if (e) e.preventDefault();
    if (!code.trim()) {
      setError("Please enter the pairing code displayed by your desktop agent.");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      await verifyDeviceCode(code.trim().toUpperCase());
      setSuccess(true);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Failed to authorize device. Please check the code.";
      setError(msg);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-bg-default px-4 py-12 text-text-primary">
      <div className="relative w-full max-w-md rounded-[var(--radius-lg)] border border-border-default bg-bg-secondary p-7 shadow-lg space-y-6">
        
        {/* Header */}
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-[var(--radius-sm)] bg-accent-subtle text-accent-default border border-accent-default/20">
            <Laptop size={18} />
          </div>
          <div>
            <h1 className="text-sm font-semibold tracking-tight text-text-primary">ProductiveHix</h1>
            <p className="text-xs text-text-tertiary">Device Authorization</p>
          </div>
        </div>

        {success ? (
          <div className="space-y-5 text-center">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-success-bg-subtle text-success border border-success/20">
              <CheckCircle2 size={24} />
            </div>

            <div className="space-y-1.5">
              <h2 className="text-base font-semibold tracking-tight text-text-primary">Device Connected</h2>
              <p className="text-xs text-text-secondary">
                Your Windows Desktop Bridge (<span className="font-mono text-text-primary">{code.toUpperCase()}</span>) is now securely paired.
              </p>
            </div>

            <div className="rounded-[var(--radius-md)] border border-border-subtle bg-bg-inset p-3.5 text-left text-xs text-text-secondary space-y-2">
              <div className="flex items-center gap-2 text-success font-medium">
                <span className="h-1.5 w-1.5 rounded-full bg-success animate-pulse" />
                Telemetry Synchronization Active
              </div>
              <p className="text-[11px] text-text-tertiary">
                ActivityWatch window and AFK events are streaming through the local Express bridge.
              </p>
            </div>

            <button
              onClick={() => router.push("/")}
              className="inline-flex w-full items-center justify-center gap-2 rounded-[var(--radius-sm)] bg-accent-default py-2.5 text-xs font-medium text-white transition hover:bg-accent-hover"
            >
              Open Dashboard <ArrowRight size={14} />
            </button>
          </div>
        ) : (
          <form onSubmit={handleApprove} className="space-y-5">
            <div className="space-y-1.5">
              <h2 className="text-base font-semibold tracking-tight text-text-primary">Pair Desktop Bridge</h2>
              <p className="text-xs text-text-secondary leading-relaxed">
                Enter the authorization code generated by your local Windows ActivityWatch bridge.
              </p>
            </div>

            {error && (
              <div className="flex items-start gap-2.5 rounded-[var(--radius-sm)] border border-error/20 bg-error-bg-subtle p-3 text-xs text-error">
                <AlertCircle size={14} className="shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            <div className="space-y-1.5">
              <label htmlFor="userCode" className="block text-[11px] font-medium uppercase tracking-wider text-text-tertiary">
                Pairing Code
              </label>
              <input
                id="userCode"
                type="text"
                value={code}
                onChange={(e) => setCode(e.target.value.toUpperCase())}
                placeholder="PHIX-XXXX"
                className="w-full rounded-[var(--radius-sm)] border border-border-strong bg-bg-inset px-3 py-2 text-center font-mono text-base font-semibold tracking-widest text-text-primary outline-none focus:border-accent-default transition"
                maxLength={10}
                required
              />
            </div>

            <div className="rounded-[var(--radius-md)] border border-border-subtle bg-bg-inset p-3 space-y-1.5 text-xs text-text-secondary">
              <div className="flex items-center gap-1.5 text-text-primary font-medium">
                <ShieldCheck size={13} className="text-accent-default" />
                Permissions:
              </div>
              <ul className="list-disc pl-4 space-y-1 text-[11px] text-text-tertiary">
                <li>Read local ActivityWatch window & AFK telemetry</li>
                <li>Stream normalized activity batches via WebSocket</li>
              </ul>
            </div>

            <button
              type="submit"
              disabled={loading || !code.trim()}
              className="inline-flex w-full items-center justify-center gap-2 rounded-[var(--radius-sm)] bg-accent-default py-2.5 text-xs font-medium text-white transition hover:bg-accent-hover disabled:opacity-50"
            >
              {loading ? (
                <>
                  <Loader2 size={14} className="animate-spin" /> Authorizing...
                </>
              ) : (
                "Authorize Device"
              )}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}

export default function PairDevicePage() {
  return (
    <Suspense fallback={
      <div className="flex min-h-screen items-center justify-center bg-bg-default text-text-tertiary">
        <Loader2 className="animate-spin" size={20} />
      </div>
    }>
      <PairDeviceContent />
    </Suspense>
  );
}
